const D={"香港島":["中西區","灣仔區","東區","南區"],"九龍":["油尖旺區","深水埗區","九龍城區","黃大仙區","觀塘區"],"新界":["葵青區","荃灣區","屯門區","元朗區","北區","大埔區","沙田區","西貢區","離島區"]};
const EN={"中西區":"Central and Western","灣仔區":"Wan Chai","東區":"Eastern","南區":"Southern","油尖旺區":"Yau Tsim Mong","深水埗區":"Sham Shui Po","九龍城區":"Kowloon City","黃大仙區":"Wong Tai Sin","觀塘區":"Kwun Tong","葵青區":"Kwai Tsing","荃灣區":"Tsuen Wan","屯門區":"Tuen Mun","元朗區":"Yuen Long","北區":"North","大埔區":"Tai Po","沙田區":"Sha Tin","西貢區":"Sai Kung","離島區":"Islands"};
const HINT={"香港島":"中環、上環、半山 → 中西區","九龍":"旺角、尖沙咀、油麻地 → 油尖旺區","新界":"東涌／大嶼山／長洲 → 離島區 · 將軍澳 → 西貢區 · 天水圍 → 元朗區 · 青衣 → 葵青區"};
const P=["https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=70","https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&q=70","https://images.unsplash.com/photo-1503602642458-232111445657?w=600&q=70","https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=600&q=70","https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&q=70","https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=600&q=70"];
const ST={open:"待認領",locked:"鎖定待交收",done:"已完成交收"};
const CONDS=["全新","9成新","8成新","7成新","有破損"];
const CATS=["家品","電子","衣物","書本","玩具","廚具","其他"];
const MEETS=["面交","自取","地鐵站交收","屋苑大堂"];
const PLANS=[{id:"w",name:"每星期",price:"US$1",note:"發佈同認領都包。睇牆不收"},{id:"m",name:"每月",price:"US$3",note:"對照用，等同 75 美仙／星期"},{id:"y",name:"每年",price:"US$40",note:"對照用，等同 77 美仙／星期"}];
let plan="w", alerts=true, paid=localStorage.getItem("fa_paid")==="1", pending=null;
const SEED=[
 {id:11,title:"IKEA 層架",cond:"8成新",cat:"家品",dist:"離島區",km:"1.2km",when:"12分鐘",meet:"東涌站",user:"Katy",desc:"東涌站 B 出口。",photos:[P[1],P[0],P[2]],status:"open",x:62,y:70},
 {id:12,title:"嬰兒車",cond:"7成新",cat:"玩具",dist:"離島區",km:"0.8km",when:"28分鐘",meet:"逸東大堂",user:"阿琳",desc:"逸東邨大堂自取。",photos:[P[2],P[1],P[0]],status:"open",x:48,y:62},
 {id:13,title:"單車",cond:"8成新",cat:"其他",dist:"離島區",km:"2.4km",when:"1小時",meet:"東涌北",user:"Tom",desc:"要自己推走。",photos:[P[3],P[2],P[1]],status:"open",x:70,y:48},
 {id:14,title:"實木餐椅兩張",cond:"8成新",cat:"家品",dist:"沙田區",km:"18km",when:"今日",meet:"沙田圍站",user:"阿琳",desc:"沙田圍站交收。",photos:[P[0],P[1],P[2]],status:"open",x:58,y:28},
 {id:15,title:"書一箱",cond:"9成新",cat:"書本",dist:"中西區",km:"28km",when:"今日",meet:"上環",user:"May",desc:"文學書為主。",photos:[P[4],P[5],P[0]],status:"open",x:42,y:58},
 {id:16,title:"盆栽",cond:"全新",cat:"家品",dist:"油尖旺區",km:"22km",when:"2小時",meet:"旺角",user:"Ken",desc:"尖沙咀交。",photos:[P[5],P[0],P[1]],status:"open",x:46,y:42},
 {id:17,title:"電燒壺",cond:"7成新",cat:"廚具",dist:"葵青區",km:"14km",when:"今日",meet:"青衣",user:"阿珍",desc:"可用，有少少水垢。",photos:[P[1],P[2],P[5]],status:"open",x:36,y:36},
 {id:18,title:"小書架",cond:"9成新",cat:"家品",dist:"西貢區",km:"16km",when:"3小時",meet:"將軍澳",user:"Sam",desc:"坑口站交。",photos:[P[2],P[4],P[0]],status:"open",x:72,y:34}
];
let items; try{items=JSON.parse(localStorage.getItem("fa_v12")||"null")||SEED}catch(e){items=SEED}
let cur=null, picked="離島區", sheetMode="filter";
let draft={photos:[null,null,null,null],cond:"8成新",cat:"家品",dist:"",meet:"面交"};
let photoSlot=0;
function save(){try{localStorage.setItem("fa_v12",JSON.stringify(items))}catch(e){}}
function clay(id,fill,d){return '<svg class="clay" viewBox="0 0 32 32" aria-hidden="true"><defs><linearGradient id="'+id+'" x1="6" y1="2" x2="26" y2="30"><stop offset="0" stop-color="'+fill[0]+'"/><stop offset="1" stop-color="'+fill[1]+'"/></linearGradient></defs><path fill="url(#'+id+')" d="'+d+'"/></svg>'}
const ICO={home:clay('gH',['#86e0ab','#1a6b43'],'M6 14.2L16 6l10 8.2V26a2 2 0 0 1-2 2H19v-8h-6v8H8a2 2 0 0 1-2-2z'),pulse:clay('gP',['#8fe3c0','#1f7a52'],'M4 16h4l3-8 4 16 3-8h10v3H20l-3 8-4-16-3 8H4z'),chat:clay('gC',['#9be4c4','#1a6b43'],'M6 7.5A5.5 5.5 0 0 1 11.5 2h9A5.5 5.5 0 0 1 26 7.5v8A5.5 5.5 0 0 1 20.5 21H13l-7 5V7.5z'),me:clay('gM',['#b7ebcf','#1f6b45'],'M16 4.5a5 5 0 1 1 0 10 5 5 0 0 1 0-10zM7.5 27c1.6-5 4.3-7.5 8.5-7.5s6.9 2.5 8.5 7.5z'),plus:clay('gX',['#fff8ee','#f0e2cc'],'M14 7h4v18h-4zM7 14h18v4H7z'),heart:clay('gR',['#ff9aa0','#c4454a'],'M16 27S6 20.2 6 13.2A5.4 5.4 0 0 1 16 10a5.4 5.4 0 0 1 10 3.2C26 20.2 16 27 16 27z')};
function paintIcons(){document.querySelectorAll(".tab").forEach(t=>{const n=t.getAttribute("data-tab")||"發現";const map={"發現":ICO.home,"動態":ICO.pulse,"對話":ICO.chat,"個人":ICO.me};if(map[n]) t.innerHTML=map[n]+'<span>'+n+'</span>';});document.querySelectorAll(".sell-fab").forEach(b=>{b.innerHTML=ICO.plus;b.onclick=goPost});const fav=document.querySelector(".ghost-ico");if(fav) fav.innerHTML=ICO.heart;}
function show(id){document.querySelectorAll(".screen").forEach(s=>s.classList.remove("on"));document.getElementById(id).classList.add("on");paintIcons();if(id==="home")feed();if(id==="me")me();if(id==="pay")renderPlans();if(id==="activity")activity();if(id==="chats")document.getElementById("chatList").innerHTML="<p class='sub' style='padding:16px'>對話係認領之後先開。睇牆不使付費。</p>";if(id==="post")setupPost();}
function needPay(why){if(paid) return false;pending=why;const t=document.getElementById("payTitle");const lead=document.getElementById("payLead");if(t) t.innerHTML=why==="post"?"要發佈呢件，<br/>先要付費。":"要認領呢件，<br/>先要付費。";if(lead) lead.textContent="睇牆、搜尋、睇相不收費。發佈同認領用同一個方案。物品永遠 $0。";show("pay");return true}
function goPost(){if(needPay("post")) return;show("post")}
function unlockDemo(){paid=true;localStorage.setItem("fa_paid","1");toast("示範已解鎖發佈／認領");if(pending==="post"){pending=null;show("post")}else if(pending==="claim"&&cur){pending=null;lock()}else show("home")}
function toast(t){const el=document.getElementById("toast");el.textContent=t;el.style.display="block";el.classList.add("show");setTimeout(()=>{el.style.display="none";el.classList.remove("show")},1600)}
function renderPlans(){const el=document.getElementById("plans");if(!el)return;el.innerHTML=PLANS.map(p=>`<button class="plan${plan===p.id?' on':''}" onclick="plan='${p.id}';renderPlans()"><b>${p.price} / ${p.name}</b><span>${p.note}</span></button>`).join("")}
function mapPins(){const box=document.getElementById("mapbox");if(!box)return;const list=items.filter(it=>it.status!=="done"&&(picked==="全部"||it.dist===picked)&&it.x);box.innerHTML=list.map(it=>`<button class="pin" style="left:${it.x}%;top:${it.y}%" onclick="openItem(${it.id})">${it.km}</button>`).join("")||"<div class='sub' style='padding:16px'>呢區暫時無針</div>";}
function feed(){const loc=document.querySelector(".loc");if(loc) loc.innerHTML=(picked==="全部"?"十八區":picked)+' ▾<small>'+(picked==="離島區"?"東涌":"香港")+' · 睇牆免費</small>';const bar=document.getElementById("filterBar");if(bar) bar.innerHTML=`<button class='chip on'>可睇</button><button class='chip' onclick="openSheet('filter')">${picked==="全部"?"十八區":picked}</button><button class='chip' onclick="show('pay')">${paid?'已開通送／執':'送／執要付費'}</button>`;mapPins();const q=(document.getElementById("q")?.value||"").trim();const list=items.filter(it=>it.status!=="done"&&(picked==="全部"||it.dist===picked)&&(!q||(it.title+it.dist+(it.cat||"")).includes(q)));document.getElementById("feed").innerHTML=list.map(it=>`<article class="card" onclick="openItem(${it.id})"><div class="ph" style="background-image:url('${it.photos[0]}')"><span class="badge">${it.cond}</span><button class="heart" onclick="event.stopPropagation();toast('已收藏')">${ICO.heart}</button></div><div class="meta"><div class="free">免費 · ${it.km||""}</div><h3>${it.title}</h3><div class="seller">${it.user} · ${it.dist} · ${it.when||""}</div></div></article>`).join("")||"<p class='sub'>呢區暫時無物品。</p>";}
function activity(){const el=document.getElementById("activityList");if(!el)return;el.innerHTML=items.slice(0,4).map(it=>`<div class="row" onclick="openItem(${it.id})"><div class="ava">新</div><div><b>${it.dist} 有人送「${it.title}」</b><div class="sub">${it.when||""} · ${it.km||""}</div></div></div>`).join("")}
function openItem(id){cur=items.find(x=>x.id===id);if(!cur)return;document.getElementById("gallery").style.backgroundImage=`url('${cur.photos[0]}')`;document.getElementById("detailSheet").innerHTML=`<h2>${cur.title}</h2><div class="tagrow"><span class="tag ${cur.status}">${ST[cur.status]}</span><span class="tag">${cur.cond}</span><span class="tag alt">${cur.dist} · ${cur.km||""}</span><span class="tag">${cur.cat||"家品"}</span><span class="tag">${cur.meet||"面交"}</span></div><div class="desc">${cur.desc||""}</div><div class="status-box"><b>睇得到，不使付費</b><div class="sub">認領先鎖定。物品不可標價。</div></div>`;const giver=cur.user==="你";document.getElementById("detailCta").innerHTML=cur.status==="done"?"<button class='btn btn-ghost' onclick=\"show('home')\">返發現</button>":cur.status==="locked"?`<div class="btn-row"><button class="btn btn-primary" onclick="done()">確認完成交收</button>${giver?"<button class='btn btn-warn' onclick='cancel()'>取消鎖定</button>":""}</div>`:`<button class="btn btn-primary" onclick="lock()">認領（要付費）</button>`;show("detail")}
function lock(){if(needPay("claim")) return;cur.status="locked";save();toast("已鎖定待交收");openItem(cur.id)}
function done(){cur.status="done";save();toast("已完成交收");openItem(cur.id)}
function cancel(){if(cur.user!=="你"){toast("只有發佈者可取消");return}cur.status="open";save();toast("已回復待認領");openItem(cur.id)}
function giveCount(){return items.filter(it=>it.user==="你"&&it.status==="done").length}
function toggleAlert(){alerts=!alerts;toast(alerts?"附近新帖會提醒":"已關提醒");me()}
function me(){document.getElementById("trialLeft").textContent=paid?"已開通發佈／認領":"未開通發佈／認領";const n=giveCount();document.getElementById("stGive").textContent=String(n);document.getElementById("meGiveBadge").textContent=String(n);const a=document.getElementById("alertState");if(a) a.textContent=alerts?"開":"關";const mine=items.filter(it=>it.user==="你");document.getElementById("myListings").innerHTML=mine.length?mine.map(it=>`<div class="row" onclick="openItem(${it.id})"><div class="ava">物</div><div><b>${it.title}</b><div class="sub">${ST[it.status]} · ${it.dist}</div></div></div>`).join(""):"<p class='sub' style='padding:12px 0'>未有你發佈的物品。</p>"}
function openSheet(mode){sheetMode=mode||"filter";let html="<div class='grab'></div><div class='sheet-head'><b>香港十八區</b><span class='sub'>官方地方行政區（區議會條例）</span></div>";if(sheetMode==="filter") html+="<button class='dist-all' onclick=\"pickDist('全部')\">全部十八區</button>";for(const [g,list] of Object.entries(D)){html+=`<div class='dist-reg'>${g}<small>${HINT[g]}</small></div><div class='dist-grid'>`+list.map(d=>`<button class='dist-tile' onclick=\"pickDist('${d}')\"><b>${d}</b><span>${EN[d]}</span></button>`).join("")+"</div>"}document.getElementById("modalBody").innerHTML=html;document.getElementById("modal").classList.add("on")}
function pickDist(d){if(sheetMode==="post"){draft.dist=d;document.getElementById("pDistrictBtn").textContent=d;toast("交收區："+d)}else{picked=d;toast(d==="全部"?"已選全部十八區":"已選 "+d);feed()}closeSheet()}
function closeSheet(){document.getElementById("modal").classList.remove("on")}
function chips(el,arr,key){el.innerHTML=arr.map(v=>`<button type="button" class="opt${draft[key]===v?' on':''}" onclick="draft.${key}='${v}';chips(document.getElementById('${el.id}'),${JSON.stringify(arr).replace(/"/g,"'")},'${key}')">${v}</button>`).join("")}
function setupPost(){document.getElementById("pErr").textContent="";renderSlots();chips(document.getElementById("condOpts"),CONDS,"cond");chips(document.getElementById("catOpts"),CATS,"cat");chips(document.getElementById("meetOpts"),MEETS,"meet");document.getElementById("pDistrictBtn").textContent=draft.dist||"選擇十八區"}
function renderSlots(){document.getElementById("photoSlots").innerHTML=draft.photos.map((src,i)=>`<button type="button" class="ph-slot${src?' filled':''}" style="${src?'background-image:url('+src+')':''}" onclick="pickPhoto(${i})">${src?'':'+相'}</button>`).join("")}
function pickPhoto(i){photoSlot=i;const inp=document.getElementById("filePick");inp.onchange=()=>{const f=inp.files&&inp.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{draft.photos[photoSlot]=r.result;renderSlots()};r.readAsDataURL(f);inp.value=""};inp.click()}
function useDemoPhotos(){draft.photos=[P[0],P[1],P[2],null];renderSlots();toast("已用示範三張相")}
function submitPost(){if(needPay("post")) return;const title=(document.getElementById("pTitle").value||"").trim();const desc=(document.getElementById("pDesc").value||"").trim();const pics=draft.photos.filter(Boolean);const err=document.getElementById("pErr");if(pics.length<3){err.textContent="最少要 3 張相";return}if(!title){err.textContent="請寫標題";return}if(!draft.dist){err.textContent="請選交收區";return}if(!document.getElementById("pFree").checked){err.textContent="物品必須完全免費";return}items.unshift({id:Date.now(),title,desc,cond:draft.cond,cat:draft.cat,dist:draft.dist,meet:draft.meet,user:"你",photos:pics,status:"open",km:"附近",when:"剛剛",x:55,y:55});save();draft={photos:[null,null,null,null],cond:"8成新",cat:"家品",dist:"",meet:"面交"};document.getElementById("pTitle").value="";document.getElementById("pDesc").value="";toast("已發佈，等人認領");show("home")}
function sendMsg(){toast("示範對話")}
paintIcons();
