const ASHE='<svg viewBox="0 0 64 64" aria-hidden="true"><circle cx="32" cy="32" r="32" fill="#e7e7ea"/><ellipse cx="32" cy="36" rx="18" ry="16" fill="#f4f4f5"/><path d="M16 28l4-14 8 8zM48 28l-4-14-8 8z" fill="#d7d7dc"/><circle cx="25" cy="34" r="5" fill="#222"/><circle cx="39" cy="34" r="5" fill="#222"/><circle cx="26.5" cy="32.5" r="1.4" fill="#fff"/><circle cx="40.5" cy="32.5" r="1.4" fill="#fff"/><path d="M29 42c2 2 4 2 6 0" stroke="#222" fill="none" stroke-width="1.4"/><path d="M18 48c4 8 24 8 28 0v10H18z" fill="#1f8a4c"/></svg>';
function paintAshe(){document.querySelectorAll(".logo").forEach(el=>{el.innerHTML=ASHE; el.style.padding="0"; el.style.overflow="hidden";});}
function homeBadges(){const home=document.getElementById("home"); if(!home||document.getElementById("homeRank")) return; const bar=document.createElement("div"); bar.id="homeRank"; bar.className="home-rank"; const g=typeof giveLv==="function"?giveLv():1; const t=typeof takeLv==="function"?takeLv():1; const tr=typeof trust==="number"?trust:100; bar.innerHTML=ASHE+'<div><b>📦 Lv.'+g+' · 🙋 Lv.'+t+'</b><span>誠信度 '+tr+'%</span></div>'; home.insertBefore(bar, home.querySelector(".mapbox"));}
function rules(){if(localStorage.getItem("fa_rules")==="1") return; const body=document.getElementById("modalBody"); if(!body) return; body.innerHTML='<div class="grab"></div><b>入屋前必讀</b><p class="sub">物品只限免費自用。轉賣會封號。放飛機扣 20% 誠信度。新丁有一次免死金牌。</p><button class="btn btn-primary" onclick="localStorage.setItem(\'fa_rules\',\'1\');closeSheet()">同意，開始斷捨離</button>'; document.getElementById("modal").classList.add("on");}
const _act=activity;
activity=function(){const el=document.getElementById("activityList"); if(!el) return; el.innerHTML=['交收前 3 小時：時間寶貴，記住同街坊有約','交收前 30 分鐘：差唔多出發未','正點：夠鐘啦，到咗记得打卡','逾時 15 分鐘：再唔出現當放飛機','搞搞震：評下街坊，賺經驗'].map(t=>'<div class="row"><div class="ava">'+ASHE+'</div><div><b>阿捨</b><div class="sub">'+t+'</div></div></div>').join("");};
const _showAshe=show;
show=function(id){_showAshe(id); paintAshe(); if(id==="home"){homeBadges(); rules();}};
paintAshe();
const st=document.createElement("style"); st.textContent=".logo{width:36px;height:36px;border-radius:18px}.logo svg{width:36px;height:36px;display:block}.home-rank{display:flex;gap:10px;align-items:center;margin:8px 16px 0;background:#fff;border:1px solid var(--line);border-radius:16px;padding:8px 10px}.home-rank svg{width:36px;height:36px}.home-rank b{display:block;font-size:13px}.home-rank span{color:#6e6e73;font-size:12px}"; document.head.appendChild(st);
